import { NextResponse } from 'next/server';
import { authenticate, ApiError, assertSectionOwner, requireClinic, requireRole } from '../../lib/auth';
import type { Candidate, UserContext } from '../../lib/types';
import { scoreImportance, decayTier } from '../../lib/importance';
import { redactBeforeModel } from '../../lib/redaction';
import { audit, ensureDatabase, id, resetDemo, run } from '../../db/store';

export const dynamic = 'force-dynamic';

function json(data: unknown, status = 200, headers: Record<string,string> = {}) {
  return NextResponse.json(data, {
    status,
    headers: {
      'cache-control': 'private, no-store',
      'x-content-type-options': 'nosniff',
      'referrer-policy': 'no-referrer',
      ...headers,
    },
  });
}
function errorResponse(error: unknown) { if (error instanceof ApiError) return json({ error: error.message }, error.status); console.error(error); return json({ error: 'Internal server error' }, 500); }
async function body(request: Request) { try { return await request.json() as Record<string, unknown>; } catch { throw new ApiError(400, 'Valid JSON body required.'); } }
async function patientFor(db: D1Database, user: UserContext, patientId: string) { const patient = await db.prepare('SELECT * FROM patients WHERE id = ?').bind(patientId).first<Record<string, unknown>>(); if (!patient) throw new ApiError(404, 'Patient not found.'); requireClinic(user, String(patient.clinic_id)); if (user.role === 'patient' && user.patientId !== patientId) throw new ApiError(404, 'Patient not found.'); return patient; }
function parseRows<T extends Record<string, unknown>>(rows: T[]) { return rows.map(row => { const copy: Record<string, unknown> = { ...row }; for (const key of Object.keys(copy)) if (key.endsWith('_json') && typeof copy[key] === 'string') { try { copy[key.replace('_json','')] = JSON.parse(copy[key] as string); } catch {} } return copy; }); }
async function learningAdjustment(db: D1Database, clinicId: string, topic: string) { const result = await db.prepare('SELECT COALESCE(SUM(weight),0) AS weight FROM highlight_feedback WHERE clinic_id = ? AND topic = ?').bind(clinicId, topic).first<{ weight: number }>(); return Number(result?.weight ?? 0); }

export async function GET(request: Request) {
  try {
    const user = authenticate(request); const db = await ensureDatabase(); const url = new URL(request.url); const action = url.searchParams.get('action') ?? 'bootstrap'; const patientId = url.searchParams.get('patient_id') ?? 'patient-1';
    if (action === 'health') return json({ status: 'ok', syntheticDataOnly: true });
    if (action === 'bootstrap') {
      const patient = await patientFor(db, user, patientId);
      if (user.role === 'patient') {
        const summaries = await db.prepare("SELECT id, content, approved_at, source_entry_ids_json FROM patient_summaries WHERE patient_id = ? AND clinic_id = ? AND status = 'approved' ORDER BY approved_at DESC").bind(patientId, user.clinicId).all<Record<string, unknown>>();
        return json({ user, patient, patientView: true, summaries: parseRows(summaries.results), safetyNotice: 'Only clinician-approved information is shown. Raw AI notes and internal comments are withheld.' });
      }
      const [entries, sections, highlights, tasks, comments, conflicts, team] = await Promise.all([
        db.prepare('SELECT * FROM entries WHERE patient_id = ? AND clinic_id = ? ORDER BY timestamp DESC').bind(patientId,user.clinicId).all<Record<string,unknown>>(),
        db.prepare('SELECT * FROM care_sections WHERE patient_id = ? AND clinic_id = ? ORDER BY section_key').bind(patientId,user.clinicId).all<Record<string,unknown>>(),
        db.prepare("SELECT * FROM highlights WHERE patient_id = ? AND clinic_id = ? AND status != 'rejected' ORDER BY importance_score DESC LIMIT 6").bind(patientId,user.clinicId).all<Record<string,unknown>>(),
        db.prepare("SELECT tasks.*, users.name AS assignee_name FROM tasks LEFT JOIN users ON users.id=tasks.assignee_id WHERE tasks.patient_id = ? AND tasks.clinic_id = ? AND tasks.status != 'done' ORDER BY tasks.due_at").bind(patientId,user.clinicId).all<Record<string,unknown>>(),
        db.prepare('SELECT comments.*, users.name AS author_name FROM comments LEFT JOIN users ON users.id=comments.author_id WHERE comments.clinic_id = ? AND (comments.entry_id IN (SELECT id FROM entries WHERE patient_id = ?) OR comments.section_id IN (SELECT id FROM care_sections WHERE patient_id = ?)) ORDER BY comments.created_at DESC').bind(user.clinicId,patientId,patientId).all<Record<string,unknown>>(),
        db.prepare("SELECT * FROM conflicts WHERE patient_id = ? AND clinic_id = ? AND status = 'open'").bind(patientId,user.clinicId).all<Record<string,unknown>>(),
        db.prepare('SELECT id,name,role FROM users WHERE clinic_id = ? ORDER BY role,name').bind(user.clinicId).all<Record<string,unknown>>(),
      ]);
      return json({ user, patient, patientView: false, entries: entries.results, sections: sections.results, highlights: highlights.results, tasks: tasks.results, comments: parseRows(comments.results), conflicts: conflicts.results, team: team.results });
    }
    if (action === 'glance') {
      await patientFor(db,user,patientId); if (user.role === 'patient') throw new ApiError(403,'Patients use the approved patient summary endpoint.');
      const started = performance.now();
      const result = await db.prepare("SELECT id,title,excerpt,risk_level,risk_reason,importance_score,evidence_label,evidence_score,status,provenance_pointer,category FROM highlights WHERE patient_id=? AND clinic_id=? AND status!='rejected' ORDER BY importance_score DESC LIMIT 4").bind(patientId,user.clinicId).all();
      return json({ highlights: result.results, serverQueryMs: Math.round((performance.now()-started)*100)/100 },200,{ 'server-timing': `db;dur=${(performance.now()-started).toFixed(2)}` });
    }
    if (action === 'comments') { requireRole(user,['staff','clinician','admin']); await patientFor(db,user,patientId); const rows = await db.prepare('SELECT * FROM comments WHERE clinic_id=? ORDER BY created_at DESC').bind(user.clinicId).all(); return json({ comments: rows.results }); }
    if (action === 'entry') { const entryId=url.searchParams.get('entry_id'); const entry=await db.prepare('SELECT * FROM entries WHERE id=?').bind(entryId).first<Record<string,unknown>>(); if(!entry) throw new ApiError(404,'Entry not found.'); requireClinic(user,String(entry.clinic_id)); if(user.role==='patient' && Number(entry.internal_only)) throw new ApiError(403,'Patients cannot access internal or raw AI-scribed entries.'); return json({entry}); }
    if (action === 'provenance') {
      const highlightId = url.searchParams.get('highlight_id'); const highlight = await db.prepare('SELECT * FROM highlights WHERE id=?').bind(highlightId).first<Record<string,unknown>>(); if(!highlight) throw new ApiError(404,'Highlight not found.'); requireClinic(user,String(highlight.clinic_id)); if(user.role==='patient') throw new ApiError(403,'Internal source material is not patient-visible.');
      const entry = await db.prepare('SELECT * FROM entries WHERE id=? AND clinic_id=?').bind(highlight.source_entry_id,user.clinicId).first<Record<string,unknown>>(); if(!entry) throw new ApiError(409,'Provenance target no longer resolves.'); const start=Number(highlight.source_start), end=Number(highlight.source_end), content=String(entry.content); if(start<0||end>content.length||start>=end) throw new ApiError(409,'Provenance span is invalid.');
      return json({ pointer: highlight.provenance_pointer, anchor: `entry-${entry.id}`, entry, span: { start,end,text:content.slice(start,end) }, resolves:true });
    }
    if (action === 'versions') { requireRole(user,['staff','clinician','admin']); const sectionId=url.searchParams.get('section_id'); const section=await db.prepare('SELECT * FROM care_sections WHERE id=?').bind(sectionId).first<Record<string,unknown>>(); if(!section) throw new ApiError(404,'Section not found.'); requireClinic(user,String(section.clinic_id)); const since=Number(url.searchParams.get('since')??0); const versions=await db.prepare('SELECT versions.*, users.name AS changed_by_name FROM versions LEFT JOIN users ON users.id=versions.changed_by WHERE entity_id=? AND version_number>? ORDER BY version_number DESC').bind(sectionId,since).all(); return json({section,versions:versions.results}); }
    if (action === 'audit') { requireRole(user,['clinician','admin']); const rows=await db.prepare('SELECT audit_logs.*, users.name AS actor_name FROM audit_logs LEFT JOIN users ON users.id=audit_logs.actor_id WHERE audit_logs.clinic_id=? ORDER BY created_at DESC LIMIT 50').bind(user.clinicId).all(); return json({audit:parseRows(rows.results as Record<string,unknown>[])}); }
    if (action === 'importance_preview') { requireRole(user,['staff','clinician','admin']); const topic=url.searchParams.get('topic')??'ace_cough'; const category=(url.searchParams.get('category')??'symptom') as Candidate['category']; const learned=await learningAdjustment(db,user.clinicId,topic); const result=scoreImportance({topic,category,riskLevel:(url.searchParams.get('risk')??'moderate') as Candidate['riskLevel'],recencyDays:1,unresolvedTask:false,clinicianConfirmed:false,evidenceCoverage:.82,evidenceQuality:.86},learned); return json({topic,...result,guardrails:{exposureBias:'No penalty for unseen items',fatigue:'Critical classes retain deterministic floors'}}); }
    if (action === 'decay_preview') { requireRole(user,['staff','clinician','admin']); await patientFor(db,user,patientId); const rows=await db.prepare("SELECT id,type,timestamp,storage_tier FROM entries WHERE patient_id=? AND clinic_id=? ORDER BY timestamp DESC").bind(patientId,user.clinicId).all<Record<string,unknown>>(); const now=new Date('2026-08-27T12:00:00+08:00').getTime(); return json({policy:'Full source is never deleted by the prototype; cold bodies are compression candidates with reversible pointers.',entries:rows.results.map(row=>{const ageDays=Math.floor((now-new Date(String(row.timestamp)).getTime())/86400000); const critical=String(row.type).includes('clinician'); return {...row,ageDays,...decayTier({ageDays,category:critical?'allergy':'general',unresolved:false,clinicianConfirmed:critical,score:critical?94:30})};})}); }
    throw new ApiError(404,'Unknown API action.');
  } catch (error) { return errorResponse(error); }
}

export async function POST(request: Request) {
  try {
    const user=authenticate(request); const db=await ensureDatabase(); const url=new URL(request.url); const action=url.searchParams.get('action'); const input=await body(request);
    if(action==='reset'){ requireRole(user,['admin']); await resetDemo(); return json({ok:true}); }
    if(action==='add_entry'){
      requireRole(user,['staff','clinician','admin']); const patientId=String(input.patient_id??'patient-1'); await patientFor(db,user,patientId); const requestedType=String(input.type??''); const allowed=user.role==='staff'?['staff_note']:user.role==='clinician'?['clinician_note']:['staff_note','clinician_note','system_event']; if(!allowed.includes(requestedType)) throw new ApiError(403,`${user.role} cannot author ${requestedType}.`); const content=String(input.content??'').trim(); if(content.length<3) throw new ApiError(400,'Note content is required.'); const entryId=id('entry'); const now=new Date().toISOString(); const authorRole=requestedType==='clinician_note'?'clinician':requestedType==='staff_note'?'staff':'system'; await run(db,'INSERT INTO entries VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',entryId,patientId,user.clinicId,authorRole,user.id,now,requestedType,content,`entry:${entryId}#span=0-${content.length}`,null,1,1,'hot'); await audit(db,{clinicId:user.clinicId,actorId:user.id,actorRole:user.role,action:'entry.create',entityType:'entry',entityId:entryId,metadata:{type:requestedType,fields:['content','type','provenance_pointer']}}); if(input.assignment_title){ await run(db,'INSERT INTO tasks VALUES (?,?,?,?,?,?,?,?,?)',id('task'),patientId,user.clinicId,String(input.assignment_title),'open',String(input.assignee_id??'u-nurse'),String(input.due_at??now),entryId,user.id); } return json({ok:true,entry_id:entryId},201);
    }
    if(action==='add_comment'){ requireRole(user,['staff','clinician','admin']); const entryId=String(input.entry_id??''); const entry=await db.prepare('SELECT * FROM entries WHERE id=?').bind(entryId).first<Record<string,unknown>>(); if(!entry) throw new ApiError(404,'Entry not found.'); requireClinic(user,String(entry.clinic_id)); const text=String(input.body??'').trim(); if(!text) throw new ApiError(400,'Comment body is required.'); const mentions=[...text.matchAll(/@(\w+)/g)].map(x=>x[1]); const commentId=id('comment'); await run(db,'INSERT INTO comments VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',commentId,entryId,null,user.clinicId,user.id,user.role,text,JSON.stringify(mentions),input.assignee_id?String(input.assignee_id):null,0,new Date().toISOString(),null); await audit(db,{clinicId:user.clinicId,actorId:user.id,actorRole:user.role,action:'comment.create',entityType:'comment',entityId:commentId,metadata:{entry_id:entryId,mentions,assigned:Boolean(input.assignee_id)}}); return json({ok:true,comment_id:commentId},201); }
    if(action==='comment_state'){ requireRole(user,['staff','clinician','admin']); const commentId=String(input.comment_id); const comment=await db.prepare('SELECT * FROM comments WHERE id=?').bind(commentId).first<Record<string,unknown>>(); if(!comment) throw new ApiError(404,'Comment not found.'); requireClinic(user,String(comment.clinic_id)); const resolved=Boolean(input.resolved); await run(db,'UPDATE comments SET resolved=?,resolved_by=? WHERE id=?',resolved?1:0,resolved?user.id:null,commentId); await audit(db,{clinicId:user.clinicId,actorId:user.id,actorRole:user.role,action:resolved?'comment.resolve':'comment.unresolve',entityType:'comment',entityId:commentId,metadata:{resolved}}); return json({ok:true,resolved}); }
    if(action==='edit_section'){ requireRole(user,['staff','clinician','admin']); const sectionId=String(input.section_id); const section=await db.prepare('SELECT * FROM care_sections WHERE id=?').bind(sectionId).first<Record<string,unknown>>(); if(!section) throw new ApiError(404,'Section not found.'); requireClinic(user,String(section.clinic_id)); assertSectionOwner(user,String(section.owner_role) as UserContext['role']); const expected=Number(input.expected_version); const next=expected+1; const content=String(input.content??''); const result=await db.prepare('UPDATE care_sections SET content=?,version=?,updated_by=?,updated_at=? WHERE id=? AND version=?').bind(content,next,user.id,new Date().toISOString(),sectionId,expected).run(); if(!result.meta.changes) throw new ApiError(409,`Version conflict: expected ${expected}; reload the latest section before retrying.`); await run(db,'INSERT INTO versions VALUES (?,?,?,?,?,?,?,?,?)',id('version'),'section',sectionId,next,content,user.id,new Date().toISOString(),String(input.change_summary??'Section edited'),expected); await audit(db,{clinicId:user.clinicId,actorId:user.id,actorRole:user.role,action:'section.edit',entityType:'section',entityId:sectionId,metadata:{from_version:expected,to_version:next,changed_fields:['content']}}); return json({ok:true,version:next}); }
    if(action==='revert_section'){ requireRole(user,['staff','clinician','admin']); const sectionId=String(input.section_id); const target=Number(input.version_number); const section=await db.prepare('SELECT * FROM care_sections WHERE id=?').bind(sectionId).first<Record<string,unknown>>(); if(!section) throw new ApiError(404,'Section not found.'); requireClinic(user,String(section.clinic_id)); assertSectionOwner(user,String(section.owner_role) as UserContext['role']); const version=await db.prepare('SELECT * FROM versions WHERE entity_id=? AND version_number=?').bind(sectionId,target).first<Record<string,unknown>>(); if(!version) throw new ApiError(404,'Target version not found.'); const next=Number(section.version)+1; await run(db,'UPDATE care_sections SET content=?,version=?,updated_by=?,updated_at=? WHERE id=?',String(version.content),next,user.id,new Date().toISOString(),sectionId); await run(db,'INSERT INTO versions VALUES (?,?,?,?,?,?,?,?,?)',id('version'),'section',sectionId,next,String(version.content),user.id,new Date().toISOString(),`Reverted to version ${target}`,Number(section.version)); await audit(db,{clinicId:user.clinicId,actorId:user.id,actorRole:user.role,action:'section.revert',entityType:'section',entityId:sectionId,metadata:{from_version:section.version,target_version:target,new_version:next}}); return json({ok:true,version:next,content:version.content}); }
    if(action==='highlight_feedback'){ requireRole(user,['staff','clinician','admin']); const highlightId=String(input.highlight_id); const highlight=await db.prepare('SELECT * FROM highlights WHERE id=?').bind(highlightId).first<Record<string,unknown>>(); if(!highlight) throw new ApiError(404,'Highlight not found.'); requireClinic(user,String(highlight.clinic_id)); const feedback=String(input.feedback); const weights:Record<string,number>={accept:4,pin:6,reject:-3,edit:3,comment:2}; if(!(feedback in weights)) throw new ApiError(400,'Unsupported feedback action.'); await run(db,'INSERT INTO highlight_feedback VALUES (?,?,?,?,?,?,?,?)',id('feedback'),user.clinicId,String(highlight.topic),feedback,weights[feedback],user.id,new Date().toISOString(),1); if(['accept','pin','reject'].includes(feedback)) await run(db,'UPDATE highlights SET status=? WHERE id=?',feedback==='reject'?'rejected':feedback==='pin'?'pinned':'accepted',highlightId); await audit(db,{clinicId:user.clinicId,actorId:user.id,actorRole:user.role,action:`highlight.${feedback}`,entityType:'highlight',entityId:highlightId,metadata:{topic:highlight.topic,weight:weights[feedback],bounded:true}}); return json({ok:true,feedback,weight:weights[feedback]}); }
    if(action==='manual_highlight'){ requireRole(user,['staff','clinician']); const entryId=String(input.entry_id); const entry=await db.prepare('SELECT * FROM entries WHERE id=?').bind(entryId).first<Record<string,unknown>>(); if(!entry) throw new ApiError(404,'Entry not found.'); requireClinic(user,String(entry.clinic_id)); const content=String(entry.content), start=Number(input.start), end=Number(input.end); if(start<0||end>content.length||start>=end) throw new ApiError(400,'Highlight span must resolve inside the source entry.'); const topic=String(input.topic??'ace_cough'); const learned=await learningAdjustment(db,user.clinicId,topic); const candidate:Candidate={topic,category:(input.category??'symptom') as Candidate['category'],riskLevel:(input.risk_level??'moderate') as Candidate['riskLevel'],recencyDays:0,clinicianConfirmed:user.role==='clinician',evidenceCoverage:1,evidenceQuality:.92}; const scored=scoreImportance(candidate,learned); const highlightId=id('highlight'); const pointer=`entry:${entryId}#span=${start}-${end}`; await run(db,'INSERT INTO highlights VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',highlightId,String(entry.patient_id),user.clinicId,String(input.title??'Manual clinical highlight'),content.slice(start,end),candidate.category,topic,candidate.riskLevel,scored.riskReason,scored.score,scored.deterministicFloor,scored.learnedAdjustment,scored.evidenceLabel,scored.evidenceScore,'accepted',pointer,entryId,start,end,user.role==='clinician'?1:0,new Date().toISOString()); await run(db,'INSERT INTO highlight_feedback VALUES (?,?,?,?,?,?,?,?)',id('feedback'),user.clinicId,topic,'manual_highlight',6,user.id,new Date().toISOString(),1); await audit(db,{clinicId:user.clinicId,actorId:user.id,actorRole:user.role,action:'highlight.manual',entityType:'highlight',entityId:highlightId,metadata:{source_entry_id:entryId,span:[start,end],topic}}); return json({ok:true,highlight_id:highlightId,provenance_pointer:pointer,score:scored.score},201); }
    if(action==='approve_summary'){ requireRole(user,['clinician']); const summaryId=String(input.summary_id); const summary=await db.prepare('SELECT * FROM patient_summaries WHERE id=?').bind(summaryId).first<Record<string,unknown>>(); if(!summary) throw new ApiError(404,'Summary not found.'); requireClinic(user,String(summary.clinic_id)); await run(db,"UPDATE patient_summaries SET status='approved',approved_by=?,approved_at=? WHERE id=?",user.id,new Date().toISOString(),summaryId); await audit(db,{clinicId:user.clinicId,actorId:user.id,actorRole:user.role,action:'patient_summary.approve',entityType:'patient_summary',entityId:summaryId,metadata:{human_approved:true,source_count:JSON.parse(String(summary.source_entry_ids_json)).length}}); return json({ok:true}); }
    if(action==='redact'){ const text=String(input.text??''); return json(redactBeforeModel(text)); }
    if(action==='ambient'){ const text=String(input.transcript??''); if(!text) throw new ApiError(400,'Transcript is required.'); const redaction=redactBeforeModel(text); if(redaction.reviewRequired) return json({status:'abstained',summary:null,redaction,reason:'Potential identifier remained after deterministic redaction; human review required before model processing.'},422); const sourceId=id('ambient'); return json({status:'ready_for_model',source_id:sourceId,redaction,transcript:{speakerLabels:true,timestamps:true,segments:[{speaker:user.role==='patient'?'Patient':'Clinician',start_ms:0,end_ms:4200,confidence:.91,text:redaction.redactedText}]},summary:'Deterministic demo summary only; no external LLM was called.',provenance_pointer:`session:${sourceId}#segment=0`}); }
    throw new ApiError(404,'Unknown API action.');
  } catch(error){ return errorResponse(error); }
}
